import type { Transaction } from '@/types/transaction';

/** Static seed data for the finance dashboard demo. */
export const initialTransactions: Transaction[] = [
  {
    id: 'tx-001',
    date: '2026-01-05',
    amount: 5200,
    category: 'Salary',
    type: 'income',
    description: 'January payroll',
  },
  {
    id: 'tx-002',
    date: '2026-01-08',
    amount: 89.5,
    category: 'Food',
    type: 'expense',
    description: 'Groceries',
  },
  {
    id: 'tx-003',
    date: '2026-01-12',
    amount: 120,
    category: 'Transport',
    type: 'expense',
    description: 'Transit pass',
  },
  {
    id: 'tx-004',
    date: '2026-01-18',
    amount: 650,
    category: 'Freelance',
    type: 'income',
    description: 'Design contract',
  },
  {
    id: 'tx-005',
    date: '2026-01-22',
    amount: 210,
    category: 'Shopping',
    type: 'expense',
    description: 'Winter jacket',
  },
  {
    id: 'tx-006',
    date: '2026-02-01',
    amount: 5200,
    category: 'Salary',
    type: 'income',
    description: 'February payroll',
  },
  {
    id: 'tx-007',
    date: '2026-02-06',
    amount: 145,
    category: 'Bills',
    type: 'expense',
    description: 'Electricity',
  },
  {
    id: 'tx-008',
    date: '2026-02-14',
    amount: 72.3,
    category: 'Food',
    type: 'expense',
    description: 'Dinner out',
  },
  {
    id: 'tx-009',
    date: '2026-02-20',
    amount: 400,
    category: 'Entertainment',
    type: 'expense',
    description: 'Concert tickets',
  },
  {
    id: 'tx-010',
    date: '2026-02-25',
    amount: 300,
    category: 'Health',
    type: 'expense',
    description: 'Dental checkup',
  },
  {
    id: 'tx-011',
    date: '2026-03-01',
    amount: 5200,
    category: 'Salary',
    type: 'income',
    description: 'March payroll',
  },
  {
    id: 'tx-012',
    date: '2026-03-04',
    amount: 55,
    category: 'Transport',
    type: 'expense',
    description: 'Rideshare',
  },
  {
    id: 'tx-013',
    date: '2026-03-10',
    amount: 920,
    category: 'Freelance',
    type: 'income',
    description: 'API integration project',
  },
  {
    id: 'tx-014',
    date: '2026-03-15',
    amount: 180,
    category: 'Shopping',
    type: 'expense',
    description: 'Home office chair pad',
  },
  {
    id: 'tx-015',
    date: '2026-03-22',
    amount: 62.4,
    category: 'Food',
    type: 'expense',
    description: 'Weekly groceries',
  },
  {
    id: 'tx-016',
    date: '2026-01-05',
    amount: 5200,
    category: 'Salary',
    type: 'income',
    description: 'January payroll',
  },
  {
    id: 'tx-017',
    date: '2026-01-08',
    amount: 840,
    category: 'Rent',
    type: 'expense',
    description: 'Monthly apartment rent',
  },
  {
    id: 'tx-018',
    date: '2026-01-11',
    amount: 120,
    category: 'Groceries',
    type: 'expense',
    description: 'Weekly grocery run',
  },
  {
    id: 'tx-019',
    date: '2026-01-14',
    amount: 350,
    category: 'Freelance',
    type: 'income',
    description: 'UI design gig payment',
  },
  {
    id: 'tx-021',
    date: '2026-01-17',
    amount: 59,
    category: 'Subscriptions',
    type: 'expense',
    description: 'Adobe Creative Cloud',
  },
  {
    id: 'tx-020',
    date: '2026-01-19',
    amount: 200,
    category: 'Transport',
    type: 'expense',
    description: 'Flight ticket to Bangalore',
  },
  {
    id: 'tx-022',
    date: '2026-01-22',
    amount: 90,
    category: 'Dining',
    type: 'expense',
    description: 'Team lunch outing',
  },
  {
    id: 'tx-023',
    date: '2026-01-25',
    amount: 1500,
    category: 'Freelance',
    type: 'income',
    description: 'Backend API project milestone',
  },
  {
    id: 'tx-024',
    date: '2026-01-28',
    amount: 45,
    category: 'Utilities',
    type: 'expense',
    description: 'Electricity bill',
  },
  {
    id: 'tx-025',
    date: '2026-02-01',
    amount: 5200,
    category: 'Salary',
    type: 'income',
    description: 'February payroll',
  },
  {
    id: 'tx-026',
    date: '2026-02-04',
    amount: 300,
    category: 'Shopping',
    type: 'expense',
    description: 'New mechanical keyboard',
  },
  {
    id: 'tx-027',
    date: '2026-02-07',
    amount: 75,
    category: 'Health',
    type: 'expense',
    description: 'Pharmacy — vitamins and meds',
  },
  {
    id: 'tx-028',
    date: '2026-02-10',
    amount: 500,
    category: 'Freelance',
    type: 'income',
    description: 'Logo design for startup',
  },
  {
    id: 'tx-029',
    date: '2026-02-13',
    amount: 110,
    category: 'Groceries',
    type: 'expense',
    description: 'Supermarket haul',
  },
  {
    id: 'tx-030',
    date: '2026-02-17',
    amount: 840,
    category: 'Rent',
    type: 'expense',
    description: 'Monthly apartment rent',
  },
  {
    id: 'tx-031',
    date: '2026-02-20',
    amount: 18,
    category: 'Subscriptions',
    type: 'expense',
    description: 'Spotify premium',
  },
  {
    id: 'tx-032',
    date: '2026-02-23',
    amount: 220,
    category: 'Transport',
    type: 'expense',
    description: 'Cab rides for the month',
  },
  {
    id: 'tx-033',
    date: '2026-02-26',
    amount: 800,
    category: 'Freelance',
    type: 'income',
    description: 'Dashboard component library',
  },
  {
    id: 'tx-034',
    date: '2026-03-02',
    amount: 65,
    category: 'Dining',
    type: 'expense',
    description: 'Birthday dinner with friends',
  },
  {
    id: 'tx-035',
    date: '2026-03-05',
    amount: 5200,
    category: 'Salary',
    type: 'income',
    description: 'March payroll',
  },
];
